### ISSUE TITLE
With that new update I'll experience the following issue

### ISSUE THREAD

**Issue by pascal-koehl** [RootLUG/chia_smoothie#1]
(venv) admin@ubuntu2004:~/chia_smoothie$ python3 -m chia_smoothie.force_sync
INFO:__main__:Attempting to connect to the 'node.chia.net:8444' full node
INFO:__main__:Attempting to connect to the 'introducer-eu.chia.net:8444' full node
Loaded 0 external full nodes
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/admin/chia_smoothie/chia_smoothie/force_sync.py", line 169, in <module>
    main()
  File "/home/admin/chia_smoothie/chia_smoothie/force_sync.py", line 164, in main
    r.force_resync()
  File "/home/admin/chia_smoothie/chia_smoothie/force_sync.py", line 147, in force_resync
    self.connect_to_known_nodes()
  File "/home/admin/chia_smoothie/chia_smoothie/force_sync.py", line 121, in connect_to_known_nodes
    node = next(node_chain)
StopIteration

I did a clean (re-)installation of ubuntu 20.04 on a QNAP TS-453D 8GB with Linux Station on it.
I also installed git, python, chia. As I also run chiadog, and chiaharvestergraph, I decided to run it in an (venv).

I'll hope, that you can help me there. Thx for your work!

**Comment by RootLUG** [comment]
Sorry I missed the notification about the issue. 
I am looking at it now, it looks like the height filter removes too many nodes (incorrectly) so that the list it tries to sync against is empty.

As a temporary measure, I suggest reverting into the previous version (`git checkout 6e0b3e5`) which works correctly. I will meanwhile fix the height filter problem causing this crash

**Comment by RootLUG** [comment]
I removed the code that was doing the height filtering as it appears to be highly unreliable. For example at current height (343577) all nodes are being reported as having height < 310000 which is way lower than the filtering limit. I think the data from the API is not updating the heights very often which makes all of the nodes appear to be outdated when requested.

**Comment by pascal-koehl** [comment]
Thank You for ur work. I'll try it again.
